#!/bin/sh
cd ~/dockerlab
docker build --rm -f AMPDockerFile -t cubecoders/ampbase .
docker build --rm -f AMPDockerFileDeb11 -t cubecoders/ampbase:deb11 .
docker build --rm -f AMPDockerFileJava -t cubecoders/ampbase:java .
docker build --rm -f AMPDockerFileNode -t cubecoders/ampbase:node .
docker build --rm -f AMPDockerFileXvfb -t cubecoders/ampbase:xvfb .
docker build --rm -f AMPDockerFilePython3 -t cubecoders/ampbase:python3 .
docker build --rm -f AMPDockerFileWine -t cubecoders/ampbase:wine .
docker build --rm -f AMPDockerFileWine8 -t cubecoders/ampbase:wine8 .
docker build --rm -f AMPDockerFileMono -t cubecoders/ampbase:mono .
docker build --rm -f AMPDockerFileADS -t cubecoders/ampbase:ads .

docker push -a cubecoders/ampbase
