name: build base
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
    paths:
      - base/**
      - scripts/base/ampstart.sh
permissions:
  contents: read
  packages: write

jobs:
  push:
    if: ${{ github.repository_owner == 'CubeCoders' }}
    name: 'amp:${{ matrix.base }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base:
          - debian
          - debian-13
          - ubuntu

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cubecoders
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./base/${{ matrix.base }}/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/cubecoders/amp:${{ matrix.base }}
          cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.base }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ matrix.base }}
          provenance: mode=max
          sbom: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
